### ISSUE TITLE
Plugin navigation

### ISSUE THREAD

**Issue by aquiladev** [ethereum/remix-plugin#105]
It is not possible to navigate to a new tab from plugin at this moment

**Comment by pldespaigne** [comment]
You can do `client.call('fileManager', 'switchFile', <your file path>);`, I just try it with the [debug](https://github.com/pldespaigne/remix-debug-plugin) plugin, it works like a charm !

**Comment by GrandSchtroumpf** [comment]
I think aquiladev talks about browser tabs. Which is not possible atm.

**Comment by aquiladev** [comment]
@GrandSchtroumpf is right. This is not relevant at the moment for mythx plugin
