### ISSUE TITLE
got `Error: Plugin solidity is currently deactivated. Activate it to use this method`

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-plugin#106]
this is thrown by a call to `removeView`, the plugins seems already deactivated while calling that function

**Comment by yann300** [comment]
We have this in remix-alpha currently. Not sure what is the cause..

**Comment by GrandSchtroumpf** [comment]
I think it's because the engine call the `plugin.deactivate()` [after removing the methods](https://github.com/ethereum/remix-plugin/blob/master/projects/engine/src/engine/plugin-engine.ts#L300). I'll update that tomorrow, if it's ok.
