### ISSUE TITLE
getNetworkProvider always returns 'vm'

### ISSUE THREAD

**Issue by EdsonAlcala** [ethereum/remix-plugin#117]
Hello, I'm trying to get the current provider but it always returns 'vm'

This happens with any of the following methods

const provider = await client.network.getNetworkProvider()
// OR
const provider = await client.call('network', 'getNetworkProvider')

**Comment by yann300** [comment]
Try opening the `run transaction` module and switch the environment

**Comment by yann300** [comment]
if the provider is `web3`, you can use `getEndpoint` to get the endpoint url
