### ISSUE TITLE
types for RemixTx are not correct

### ISSUE THREAD

**Issue by EdsonAlcala** [ethereum/remix-plugin#118]
I'm currently using this.client.on('udapp', 'newTransaction', async (tx: RemixTx) => { })

And when I log the tx variable the types doesn't match. In fact I had to do:

 const { hash } = tx as any

And I couldn't see the hash field in RemixTX.

Am I missing something?

Thanks

**Comment by GrandSchtroumpf** [comment]
Are you using `remix-plugin` or `@remixproject/plugin` ?

**Comment by EdsonAlcala** [comment]
@remixproject/plugin

**Comment by yann300** [comment]
@EdsonAlcala is this working now?

**Comment by EdsonAlcala** [comment]
nooo

**Comment by GrandSchtroumpf** [comment]
RemixTx type has been updated with version 0.1.17. Feel free to reopen if the issue persists
