### ISSUE TITLE
Calling udapp / getAccounts returns only one account instead of an array of accounts.

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-plugin#143]
The universaldapp.js API located at https://github.com/ethereum/remix/blob/master/remix-lib/src/universalDapp.js#L141 does return an array.
Could be an issue while sending the response over to the plugin

**Comment by GrandSchtroumpf** [comment]
Should be fixed with : https://github.com/ethereum/remix-plugin/commit/1b6b120a3a08ced74b86e466fe5eb8564d60bf85 
install @remixproject/plugin@0.1.18
