### ISSUE TITLE
How to auto-reload a plugin?

### ISSUE THREAD

**Issue by fvictorio** [ethereum/remix-plugin#162]
The readme states: 

> Note: No need to do anything if you localhost auto-reload, a new handshake will be send by the IDE.

I'm building a plugin and I'm serving it with live reload (using [devd](https://github.com/cortesi/devd/)), but the plugin doesn't updates its behavior when I change it. I have to reload the page and connect it again.

How can I make the auto-reload work? With what server did you test this?

Thanks!

**Comment by GrandSchtroumpf** [comment]
can you try `http-server` ?
- `npm install -D http-server`
- `npx http-server`

**Comment by GrandSchtroumpf** [comment]
I'll close the issue. Feel free to reopen if you consider it should still be open.
