### ISSUE TITLE
Plugin for Diamonds

### ISSUE THREAD

**Issue by mudgen** [ethereum/remix-plugin#216]
It would be great if there was a remix plugin that provided support for deploying, upgrading, viewing and managing diamonds. The Diamond Standard is here: https://github.com/ethereum/EIPs/issues/2535

"A diamond is a set of contracts that can access the same storage variables and share the same Ethereum address."

Here is an example of a tool (in Python) that helps manage diamonds: https://github.com/lampshade9909/DiamondSetter

Blog post about that tool: http://joeyzacherl.com/2020/06/diamond-setter-ethereum-smart-contract-manager/

**Comment by GrandSchtroumpf** [comment]
Hello this repository is used for the underlying engine used by Remix IDE.
If you request a new plugin please open an issue on https://github.com/ethereum/remix-ide.
Also you can follow the message from Yann300 if you want to develop this plugin or find someone to build it for you : 
https://gitter.im/ethereum/remix-dev-plugin?at=5edff3287a7f8d2d6325a5ab
