### ISSUE TITLE
Manage Permission

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-plugin#23]
~~- [ ] profile.json should contains list of plugins / methods the plugin want to use.
during a call, if the check fails (current call is not contained in the declared methods) appManager should throw a `permission` type error.~~

 - [x] if `permission` type error is thrown, IDE should catch that and display the information to the user meaningfully.

 ~~- [ ] when plugin activate the first time, a modal display the list of functions the plugin is going to use and ask approval from the user. the settings is saved in localstorage so the user is not prompted again.~~

 ~~- [ ] this approval ^ is reasked if the json changed.~~

EDIT: 19/03/2019

spec has quite changed here - @GrandSchtroumpf

 - [x]  plugin A has `permissions` flag. when true it means that appManager will request approval when plugin B want to use plugin A, 
 - [x] appManager implementation can decide whether it is one time approval or if this persisted
 - [x] more fine grained permission is still possible in each API.
 - [x] if ipfs/swarm changed access need to be approved again.

**Comment by GrandSchtroumpf** [comment]
I would like not to overload the `profile` with a list of plugin to call. It's harder for dev to maintain. And a plugin may be so big that it's going to use many plugins, but only some in a session time.
Could we have a hook on the `AppManager` that handle the permission at runtime ? And the plugin only define a `permission` flag in the `profile`.
We can store a map that keep track of the permissions based on the IPFS hashes: 
```javascript
const permissions = {
  solidity: {
    piper: piperIpfsHash,
    ethDoc: EthdocIpfsHash
  } 
}
```
If the hash has changed we ask the permission again.

**Comment by yann300** [comment]
>  And the plugin only define a permission flag in the profile.

what would be the permission flag used for?

**Comment by GrandSchtroumpf** [comment]
It tells the `AppManager` to ask or not for permission for this module.

**Comment by GrandSchtroumpf** [comment]
> appManager implementation can decide whether it is one time approval or if this persisted
>  if ipfs/swarm changed access need to be approved again.

It will be implemented inside the IDE.
