### ISSUE TITLE
Handling Exception

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-plugin#27]
Different type of exception can exists:

 - internal `catch`
 - permission
 - API level 
 - manager level (like plugin does not exists)

**Comment by GrandSchtroumpf** [comment]
Not sure to understand what should be done here ...

**Comment by yann300** [comment]
when a call is made (either by a plugin to other plugin / module, or by IDE to plugin). the call can fail.
This issue is an attempt to list all the possible reason and manage them so the caller has a good feedback

**Comment by GrandSchtroumpf** [comment]
Oh ok. For now we have an `error` value in the postMessage message. It's catched by the Extension but not by the Plugin or Module. 
**TODO** :
- Get error [here](https://github.com/ethereum/remix-plugin/blob/master/src/engine/plugin.ts#L74)
- Catch error [here](https://github.com/ethereum/remix-plugin/blob/master/src/engine/plugin.ts#L123)

**Comment by yann300** [comment]
pr https://github.com/ethereum/remix-plugin/pull/47
