### ISSUE TITLE
CanDeactivatePlugin is called with unprobable arguments

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-plugin#274]
```
async canDeactivatePlugin (from, to) {
    console.log('canDeactivatePlugin', from, to)
    return from.name === 'manager' || from.name === to.name
  }
```

In the log, `from` is the `debugger` and `to` is `vyper`.
I/e2e was indeed playing with those (activating / deactivating debugger and vyper).
but all the action came from the plugin manager, and at any moment debugger was explicitly deactivating vyper.

**Comment by GrandSchtroumpf** [comment]
Closed in favor of #278
