### ISSUE TITLE
`source` undefined

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-plugin#28]
in `remix-extension.ts`, the allowed origin was not a remix URL, 
the `source` was then undefined and all the subsequent calls silently throws.

**Comment by GrandSchtroumpf** [comment]
The problem is that I cannot throw an error if the URL is not remix, because there are plenty of messages that comes to the window all the time (mainly because of extensions). So if I throw an error I would flood the console.

**Comment by yann300** [comment]
i think i meant that here https://github.com/ethereum/remix-plugin/blob/master/src/extension-client/remix-extension.ts#L109

the function will throw if there is no source.
and https://github.com/ethereum/remix-plugin/blob/master/src/extension-client/remix-extension.ts#L113 should perhaps use `send`

**Comment by yann300** [comment]
fixed https://github.com/ethereum/remix-plugin/blob/master/src/extension-client/remix-extension.ts#L96
