### ISSUE TITLE
wrong type used CompilationFileSources

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-plugin#289]
https://github.com/ethereum/remix-plugin/blob/1904e3b07b091eaa8060532ad7c6aa714d4fda91/packages/api/src/lib/compiler/type/output.ts#L4

This should look like:
![remix](https://user-images.githubusercontent.com/6940742/101621392-fb504c80-3a15-11eb-8eb1-9df29e3fee49.png)

**Comment by bunsenstraat** [comment]
Has been fixed in PR
