### ISSUE TITLE
Plugin definition

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-plugin#31]
The JSON def contains currently `title` and `url`. It should also contain other fields like:

- maintainer company / individual
- email support
- documentation URL
- description

And we should display them meaningfully in the UI

**Comment by GrandSchtroumpf** [comment]
I would recommend to follow the name and interface of the `package.json` then : https://docs.npmjs.com/files/package.json.
- version
- contributors: `{ name, email, url }`
- homepage
- bugs: `{ url, email }`
- repository: `{ type, url }`
