### ISSUE TITLE
Hosting plugins ipfs/swarm

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-plugin#34]
Here is a naive proposal for hosting plugins in ipfs / swarm.

we would propose a tool run by all the plugin developer for:
 - pulling list of plugins content hashes from the main chain (how to build list of contract is still to be defined)
 - pulling content from ipfs / swarm and making it available tot the network.
 - an update run every x seconds for updating the list / pulling new content and removing old hashes.

Then we can build a more robust scenario on top of that.

**Comment by yann300** [comment]
Here what could probably be the first step:

- Plugin assets are uploaded to IPFS (by plugin dev) using webui.ipfs.io or similar tool (probably require us to run an IPFS nodes and also the webUI).

- Plugin dev create a PR for referencing the plugin in a specific repository. The PR contains the profile like https://github.com/ethereum/remix-ide/blob/master/src/remixAppManager.js#L77

**Comment by yann300** [comment]
cc @GrandSchtroumpf

**Comment by GrandSchtroumpf** [comment]
see https://github.com/ethereum/remix-plugins-directory
