### ISSUE TITLE
do not use stringify / parse  for message

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-plugin#39]
currently we `stringify` and `parse` the message. 
Directly using a simple object should work and would be more efficient

**Comment by GrandSchtroumpf** [comment]
Quick note : [here](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm) is the algorithm used to clone the data with `postMessage`. 
Some limitations: 
- Error and Function are not supported
- Cannot pass DOM elements
