### ISSUE TITLE
API to be added to the readme or discussed

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-plugin#56]
- [ ] udapp : 
`methods: ['runTestTx', 'getAccounts', 'createVMAccount'],`

`runTestTx` ? do we really want to have this methods?

EDIT:
`sendTransaction` instead of `runTestTx`

___

 - [ ] app :
 `methods: ['getExecutionContextProvider', 'getProviderEndpoint', 'detectNetWork', 'addProvider', 'removeProvider']`

is `app` a good name ? perhaps `context` better.

EDIT: app should be network

___

 - [ ] source highlighters : 
`methods: ['highlight', 'discardHighlight'],`

EDIT: move to editor

___

 - [ ] config : 
methods: ['get', 'set', 'remove'],

^ not sure we should make this a "default" API ... is the `config` explorer in remix IDE necessary? let's discuss that too @LianaHus @ryestew 

EDIT: we remove it

___

 - [ ] txListener : 
the description is in the read me, but the `tx` object would perhaps need to be described.

EDIT: should be in udapp ^

**Comment by yann300** [comment]
Together with `fileManager`, `txListener`, `compiler`, this is the basic API that remix IDE makes available to other plugins. They don't *have* to be implemented by an another platform but a tool which want to implement it should respect their interface

**Comment by yann300** [comment]
we have to decide:
- which API are mandatory (need to be implemented)
- which API are not mandatory, but the interface is well documented

**Comment by GrandSchtroumpf** [comment]
**Mandatory** : If we need manadatory, `fileManager` should be the only one I think.
**Interface** should be defined by `kind` :  udapp / compiler / debugger / editor / test? / txlistener?
We can use StateMixin for that : `UdappMixin` / `CompilerMixin` / `DebuggerMixin` ...

To answer questions above: 
- `app`: `context` or `fileProvider` is better. But for me this is a superset of `fileManager`, it's remix specific.
- `runTestTx`: Not sure to understand what it does...
- `highlighters `: Maybe use `editor` or something like that. With more methods exposed.
- `config`: This is one of the most popular question on remix "what is 'config'" ^^. I vote for removing it if it's not necessary.
- `txlistener`: I'll improve the documentation about the tx object : https://github.com/ethereum/remix-plugin/issues/59

**Comment by yann300** [comment]
> if we need manadatory, fileManager should be the only one I think.

+1

> UdappMixin / CompilerMixin / DebuggerMixin 

I'd prefer to keep *Mixin only for state management (like status) that any plugin/module can provide.
Udapp, Compiler, Debugger are more feature centric and should imo be managed by inheritance.
And we should not mix the feature, I mean i don't think it is good to have one plugin be compiler and debugger at the same time.

**Comment by yann300** [comment]
> app: context or fileProvider is better. But for me this is a superset of fileManager, it's remix specific.

I don't feel the functions (getExecutionContextProvider, getProviderEndpoint, ..) are remix specific. They could be implemented in EtherAtom for instance

> runTestTx: Not sure to understand what it does...

it creates a transaction if the network is not mainnet

**Comment by yann300** [comment]
> highlighters : Maybe use editor or something like that. With more methods exposed.

right

**Comment by yann300** [comment]
> config: This is one of the most popular question on remix "what is 'config'" ^^. I vote for removing it if it's not necessary.

+1

**Comment by GrandSchtroumpf** [comment]
There might be some other interfaces we want to define : 
- `test`
- `debugger`
- `analysis`
What do you think ?

**Comment by GrandSchtroumpf** [comment]
About the `editor` (previously Source Highlighters). The interface is linked to Ace. Should we try to make it interroperable with other editors (monaco, codemirror) ? If not, how a plugin can work the same on different editor ?

**Comment by yann300** [comment]
in which sense is it linked to ace? because of input params?

**Comment by GrandSchtroumpf** [comment]
Yes, because of params.

**Comment by yann300** [comment]
interfaces are `highlight (lineColumnPos, filePath, hexColor)` and `discardHighlight()`
`lineColumnPos` is  {start: { line, column }, end: { line, column }}
I don't feel it's so linked to the ace API. you would expect char position?

**Comment by GrandSchtroumpf** [comment]
I don't know how it's done in monaco, but this is the exact interface of Ace, this is why I say that. But maybe it's ok. We can implement that now, and if it becomes a problem with another editor later, we can discuss the interface at that time.

**Comment by yann300** [comment]
i think that one can be closed isn't it?

**Comment by GrandSchtroumpf** [comment]
Sure.
