### ISSUE TITLE
when a plugin edits contents of a file it always creates a copy

### ISSUE THREAD

**Issue by Janther** [ethereum/remix-plugin#93]
Even the hello world example does this.

This prompt should only appear if the file already exist.
<img width="377" alt="Screenshot 2019-06-11 09 56 59" src="https://user-images.githubusercontent.com/1022054/59232895-601cc200-8c3a-11e9-8fc6-c2f3e5fbfd71.png">

Even if the file already exists, there should be a button to overwrite the file (most likely that this is the intended use).

Also when creating a copy, the name of the plugin should be at the beginning (maybe a folder with the plugin's name).
<img width="646" alt="Screenshot 2019-06-11 09 57 17" src="https://user-images.githubusercontent.com/1022054/59232898-63b04900-8c3a-11e9-9597-2d8aaee4a8cd.png">

Having the name at the end only prevents the editor to display Solidity's grammar since the file no longer ends with `.sol`.

**Comment by ryu9827** [comment]
@Janther yes, this happens when you make a client call to set file content like this:
```
client.call("fileManager", "setFile", "fileName", "fileContent")
```
I think this is a security strategy, they do this to notify the user that "A plugin is modifying your file content. Do you want to cancel the modifying? or you want to save the (new) content to a new file? "
You can totally leave it, it takes two seconds to go away, and your new file content will replace the old one (it replaces the old one even the new one is exactly same with the old one).

**Comment by ryu9827** [comment]
But yes, I agree that the notification is not very good. Two reasons:
1. There is only "cancel" and "Save As Copy", but not "accept";
2. The notification shows up for two seconds and then disappears. I hope there is a progress bar or timer to make the process more obvious.

**Comment by Janther** [comment]
I understand the security risk, so the existence of a prompt makes sense.
What is not clear is that this prompt will close by itself and apply the changes anyway after 2 seconds.

I still think that this info is important to a user, so I believe the accept changes button would be interesting.

If there is a countdown, it should also be visible. A nice idea would be a progress bar under the notification like [Timed Notifications](https://tympanus.net/TipsTricks/CSS3TimedNotifications/) or a pie timer in an accept changes button.

**Comment by GrandSchtroumpf** [comment]
@Janther @ryu9827 Thanks for your ideas and feedbacks.
This is actually related to [remix-ide](https://github.com/ethereum/remix-ide) as it's up to the IDE to implements how it wants to deal with permission. Remix Plugin is an engine agnostic of its host IDE (RemixIDE is the first implementation of this engine).
Could you open an issue on [RemixIDE repo](https://github.com/ethereum/remix-ide) ?

**Comment by Janther** [comment]
closing as the discussion will be continued in [remix-ide](https://github.com/ethereum/remix-ide/issues/2106)
